/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package busbooking_v1.pkg0;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Pranav
 */
public class SearchPanel extends javax.swing.JPanel {
    
    //data member
        BaseFrame bFrame;
        String sql;
        Statement stmt;
        JDBC jdbc_temp = new JDBC();
        
        
        String from_value;
        String to_value;
        String Date_value;
        String bus_type_value;
        String traveller_value;
        String route_value;
        
        int TextField_width;
        
    // member functions
    public SearchPanel() {
        initComponents();
    }
    public SearchPanel(BaseFrame f)
    {
        initComponents();
        bFrame = f;
        
        TextField_width = 10;
        
        From.setColumns(TextField_width);
        From.setText("");
        
        To.setColumns(TextField_width);
        To.setText("");
        
        DateOfJourney.setColumns(TextField_width);
        DateOfJourney.setText("");
        
        Bus_type.setColumns(TextField_width);
        Bus_type.setText("");

        Traveller.setColumns(TextField_width);
        Traveller.setText("");
        
        Route.setColumns(TextField_width);
        Route.setText("");
        
        BusSelected.setColumns(TextField_width);
        BusSelected.setText("");
    }
    
    public void GenerateSearchResultinTable(Statement stmt,String sql)
    {
        String[] tableColumnsName = {"busid","bus_name","from_place","to_place","dateofjourney",
            "departure_time","arrival_time","fare","bus_Type","traveller","Seats_Booked","route"}; 
            
            DefaultTableModel aModel = (DefaultTableModel) SearchResultTable.getModel();
            
            aModel.setColumnIdentifiers(tableColumnsName);
      try
      {
                   
            ResultSet rs = stmt.executeQuery(sql);
            
            String sd [][] = new String [2][];
            
            ResultSetMetaData rsmd = rs.getMetaData();
               int colNo = rsmd.getColumnCount(); 
               while(rs.next()){
                    Object[] objects = new Object[colNo];
                    for(int i=0;i<colNo;i++)
                    {
                            objects[i]=rs.getObject(i+1);
                    }
                  aModel.addRow(objects);
                 }
                SearchResultTable.setModel(aModel);
                
          rs.close();
        }   
      catch(Exception e)
      {
          e.printStackTrace();
      }
     
    }
    
    public String GetQueryfromTextFields()
    {
        String s = "SELECT * from bus where ";
        
        from_value = From.getText();
        to_value = To.getText();
        Date_value = DateOfJourney.getText();
        
        if(from_value.length() ==0 || to_value.length() == 0 || Date_value.length()==0)
        {
            STATUS.setText("Please fill all information");
            return "";
        }
        else
        {
             STATUS.setText("");
        }
        
        bus_type_value = Bus_type.getText();
        traveller_value = Traveller.getText();
        route_value = Route.getText();
        s = s+ "from_place = '"+from_value+"' and to_place = '"+to_value+"' and "
                + "dateofjourney = '"+Date_value+"'";
        
       
        // with search filters
        if(bus_type_value.length()!=0)
        {
            s = s+"and bus_type = '"+bus_type_value+"'";
        }
        if(traveller_value.length()!=0)
        {
            s = s + "and traveller = '"+traveller_value+"'";
        }
        if(route_value.length()!=0)
        {
            s = s+ "and route = '"+route_value+"'";
        }
        s = s + ";";
       
        return s;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        From = new javax.swing.JTextField();
        To = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DateOfJourney = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Bus_type = new javax.swing.JTextField();
        Traveller = new javax.swing.JTextField();
        Route = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchResultTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        BusSelected = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        STATUS = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setText("From");

        jLabel2.setText("To");

        From.setText("jTextField1");

        To.setText("jTextField2");

        jLabel3.setText("Date Of Journey");

        DateOfJourney.setText("jTextField3");

        jLabel4.setText("Search Filters");

        jLabel5.setText("Bus_Type");

        jLabel6.setText("Traveller");

        jLabel7.setText("Route(via)");

        Bus_type.setColumns(10);
        Bus_type.setText("jTextField1");

        Traveller.setText("jTextField2");

        Route.setText("jTextField3");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SearchResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(SearchResultTable);

        jLabel8.setText("(yyyy-mm-dd)");

        BusSelected.setText("jTextField1");
        BusSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusSelectedActionPerformed(evt);
            }
        });

        jButton2.setText("Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        STATUS.setText(".");

        jLabel9.setText("(AC/NON-AC)");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("BookMyTrip");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(From, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(DateOfJourney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel10)))
                                    .addGap(71, 71, 71)
                                    .addComponent(jLabel2)
                                    .addGap(49, 49, 49)
                                    .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(9, 9, 9)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Traveller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Bus_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Route, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BusSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jButton2))
                                            .addComponent(jLabel9))))))))
                .addContainerGap(797, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(STATUS)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(From, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(DateOfJourney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bus_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Traveller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Route, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BusSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       stmt =  jdbc_temp.getConn();
       sql = GetQueryfromTextFields();
       GenerateSearchResultinTable(stmt, sql);
       jdbc_temp.CloseAll();
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BusSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusSelectedActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

            if(BusSelected.getText().length()==0 || From.getText().length()==0 || To.getText().length()==0
                    || DateOfJourney.getText().length()==0)
            {
                STATUS.setText("Please fill all information");
                return;
            }
            else
                STATUS.setText("");
            String busID = BusSelected.getText();
            SeatSelectionPage bTicket = new SeatSelectionPage(bFrame,busID);
            bFrame.remove(this);
            bFrame.add(bTicket);
            bFrame.repaint();
            bFrame.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BusSelected;
    private javax.swing.JTextField Bus_type;
    private javax.swing.JTextField DateOfJourney;
    private javax.swing.JTextField From;
    private javax.swing.JTextField Route;
    private javax.swing.JLabel STATUS;
    private javax.swing.JTable SearchResultTable;
    private javax.swing.JTextField To;
    private javax.swing.JTextField Traveller;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
