/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package busbooking_v1.pkg0;

import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Pranav
 */
public class SeatSelectionPage extends javax.swing.JPanel {
    // data members
    private BaseFrame bFrame;
    private String busID;
    private float total_fare;
    private int TextField_width;
    // member functions
    public SeatSelectionPage() {
        initComponents();
    }
    
    public SeatSelectionPage(BaseFrame f,String BID)
    {
        initComponents();
        bFrame = f;
        busID = BID;
        TextField_width = 10;
        DisplayBusDetails();
    }
    
    public boolean ValidateSeatAvailality()
    {
        if(Integer.parseInt(Seats_Available_TextField.getText()) >= Integer.parseInt(Seats_TextField.getText()))
        {
            if(Integer.parseInt(Seats_TextField.getText()) <=5)
                return true;
            else
                return false;
        }
        else
            return false;
    }
    public void DisplayBusDetails()
    {
        Seats_TextField.setColumns(TextField_width);
        Seats_TextField.setText("1");
        
        Total_Fare_TextField.setColumns(TextField_width);
        Total_Fare_TextField.setText("0");
        
        SelectedBusName.setColumns(TextField_width);
        SelectedBusName.setText("");
        
        Seats_Available_TextField.setColumns(TextField_width);
        Seats_Available_TextField.setText("");
        
        Fare_TextField.setColumns(TextField_width);
        Fare_TextField.setText("");
                
        JDBC j_temp = new JDBC();
        
        Statement stmt = j_temp.getConn();
        String sql = "select bus_name,seats_booked,fare from bus where bus_id = '"+busID +"';";
        try
        {
            ResultSet rs = stmt.executeQuery(sql);
            rs.next();
            SelectedBusName.setText(rs.getString("bus_name").toString());
            int temp = 45 - Integer.parseInt(rs.getString("seats_booked"));
            Seats_Available_TextField.setText(temp + "");
            Fare_TextField.setText(rs.getString("fare").toString());
            rs.close();
            j_temp.CloseAll();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SelectedBusName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Seats_Available_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Seats_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Fare_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Total_Fare_TextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        STATUS = new javax.swing.JLabel();

        jLabel1.setText("Bus Name");

        SelectedBusName.setEditable(false);
        SelectedBusName.setText("jTextField1");
        SelectedBusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectedBusNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Seats Available");

        Seats_Available_TextField.setEditable(false);
        Seats_Available_TextField.setText("jTextField1");

        jLabel3.setText("Seats");

        Seats_TextField.setText("jTextField2");

        jLabel4.setText("Fare per person");

        Fare_TextField.setEditable(false);
        Fare_TextField.setText("jTextField3");

        jLabel5.setText("Total Fare");

        Total_Fare_TextField.setEditable(false);
        Total_Fare_TextField.setText("jTextField4");

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        STATUS.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(STATUS)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Seats_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Total_Fare_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Seats_Available_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SelectedBusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fare_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SelectedBusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Seats_Available_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Fare_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Seats_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(Total_Fare_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(STATUS)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SelectedBusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectedBusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectedBusNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           if(ValidateSeatAvailality())
           {
               int seats = Integer.parseInt(Seats_TextField.getText());
           
            float fare = Float.parseFloat(Fare_TextField.getText());
            total_fare= seats * fare;
            Total_Fare_TextField.setText(total_fare + "");
               STATUS.setText("Seats available");
           }
           else
           {
               STATUS.setText("Seats not available");
           }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(ValidateSeatAvailality())
         {
            int seats = Integer.parseInt(Seats_TextField.getText());
            PayMentPage pPage = new PayMentPage(bFrame,busID,total_fare,seats);
            bFrame.remove(this);
            bFrame.add(pPage);
            bFrame.repaint();
            bFrame.revalidate();
            
               STATUS.setText("Seats available");
         }
         else
         {
             
               STATUS.setText("Seats not available");
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fare_TextField;
    private javax.swing.JLabel STATUS;
    private javax.swing.JTextField Seats_Available_TextField;
    private javax.swing.JTextField Seats_TextField;
    private javax.swing.JTextField SelectedBusName;
    private javax.swing.JTextField Total_Fare_TextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
