/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package busbooking_v1.pkg0;

import com.sun.javafx.geom.Vec2f;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pranav
 */
public class ViewTicketPanel extends javax.swing.JPanel {

    private BaseFrame bFrame;
    Vector<String> Ticket_Booked;
    
    public ViewTicketPanel() {
        initComponents();
    }
    public ViewTicketPanel(BaseFrame f,Vector<String> v)
    {
        initComponents();
        bFrame = f;
        Ticket_Booked = v;
        DisplayAllTickets();
    }

    public void DisplayAllTickets()
    {
        JDBC j = new JDBC();
        Statement stmt = j.getConn();
        String sql ="";
         String[] tableColumnsName = {"Ticket_ID","bus_id","person_name","address","seat_no",
            "username","account_number"}; 
            
            DefaultTableModel aModel = (DefaultTableModel) tickets_table.getModel();
            
            aModel.setColumnIdentifiers(tableColumnsName);
      try
      {
            for(int k=0;k<Ticket_Booked.size();k++)
            {
                sql="select * from ticket where ticket_id = '"+Ticket_Booked.elementAt(k)+"'";
                ResultSet rs = stmt.executeQuery(sql);

                String sd [][] = new String [2][];

                ResultSetMetaData rsmd = rs.getMetaData();
                   int colNo = rsmd.getColumnCount(); 
                   while(rs.next()){
                        Object[] objects = new Object[colNo];
                        for(int i=0;i<colNo;i++)
                        {
                                objects[i]=rs.getObject(i+1);
                        }
                      aModel.addRow(objects);
                     }
                    tickets_table.setModel(aModel);

              rs.close();
            }
        }   
      catch(Exception e)
      {
          e.printStackTrace();
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tickets_table = new javax.swing.JTable();

        tickets_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tickets_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tickets_table;
    // End of variables declaration//GEN-END:variables
}
